# fly.toml app configuration file generated for opstelling on 2024-10-23T14:39:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'opstelling'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
